name: provider
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.5.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.10
  riverpod_lint: ^2.3.8

flutter:
  uses-material-design: true
